export PATH=/bin
R=/bin/rustfs
mkdir -p /t
cd /t
echo hello world > a.txt
printf 'b\na\nc\na\n' > lines.txt
echo "==BEGIN=="

echo "==T cat";        $R cat a.txt;                       echo "==R cat $?"
echo "==T echo";       $R echo hi;                         echo "==R echo $?"
echo "==T printf";     $R printf '%s-%d\n' x 5;            echo "==R printf $?"
echo "==T true";       $R true;                            echo "==R true $?"
echo "==T false";      $R false;                           echo "==R false $?"
echo "==T pwd";        $R pwd;                             echo "==R pwd $?"
echo "==T ls";         $R ls /t;                           echo "==R ls $?"
echo "==T cp";         $R cp a.txt b.txt;                  echo "==R cp $?"
echo "==T mv";         $R mv b.txt c.txt;                  echo "==R mv $?"
echo "==T rm";         $R rm c.txt;                        echo "==R rm $?"
echo "==T mkdir";      $R mkdir d1;                        echo "==R mkdir $?"
echo "==T rmdir";      $R rmdir d1;                        echo "==R rmdir $?"
echo "==T touch";      $R touch tf;                        echo "==R touch $?"
echo "==T ln";         $R ln -s a.txt sl;                  echo "==R ln $?"
echo "==T readlink";   $R readlink sl;                     echo "==R readlink $?"
echo "==T chmod";      $R chmod 644 tf;                    echo "==R chmod $?"
echo "==T head";       $R head -1 lines.txt;               echo "==R head $?"
echo "==T tail";       $R tail -1 lines.txt;               echo "==R tail $?"
echo "==T tac";        $R tac lines.txt;                   echo "==R tac $?"
echo "==T wc";         $R wc -l lines.txt;                 echo "==R wc $?"
echo "==T tee";        $R echo z | $R tee te.txt;          echo "==R tee $?"
echo "==T stat";       $R stat a.txt;                      echo "==R stat $?"
echo "==T du";         $R du a.txt;                        echo "==R du $?"
echo "==T df";         $R df;                              echo "==R df $?"
echo "==T dd";         $R dd if=a.txt of=dd.out 2>/dev/null; echo "==R dd $?"
echo "==T grep";       $R grep a lines.txt;                echo "==R grep $?"
echo "==T sed";        $R sed s/a/X/ lines.txt;            echo "==R sed $?"
echo "==T sort";       $R sort lines.txt;                  echo "==R sort $?"
echo "==T uniq";       $R sort lines.txt | $R uniq;        echo "==R uniq $?"
echo "==T tr";         echo abc | $R tr a-z A-Z;           echo "==R tr $?"
echo "==T cut";        echo a:b:c | $R cut -d: -f2;        echo "==R cut $?"
echo "==T paste";      $R paste lines.txt;                 echo "==R paste $?"
echo "==T fold";       echo abcdef | $R fold -w2;          echo "==R fold $?"
echo "==T rev";        echo abc | $R rev;                  echo "==R rev $?"
echo "==T nl";         $R nl lines.txt;                    echo "==R nl $?"
echo "==T awk";        echo '1 2' | $R awk '{print $1+$2}'; echo "==R awk $?"
echo "==T diff";       $R diff a.txt a.txt;                echo "==R diff $?"
echo "==T comm";       $R comm lines.txt lines.txt >/dev/null 2>&1; echo "==R comm $?"
echo "==T od";         $R od -c a.txt | $R head -1;        echo "==R od $?"
echo "==T xxd";        $R xxd a.txt | $R head -1;          echo "==R xxd $?"
echo "==T hexdump";    $R hexdump a.txt | $R head -1;      echo "==R hexdump $?"
echo "==T hd";         $R hd a.txt | $R head -1;           echo "==R hd $?"
echo "==T strings";    $R strings a.txt;                   echo "==R strings $?"
echo "==T basename";   $R basename /a/b/c;                 echo "==R basename $?"
echo "==T dirname";    $R dirname /a/b/c;                  echo "==R dirname $?"
echo "==T realpath";   $R realpath a.txt;                  echo "==R realpath $?"
echo "==T base64";     echo hi | $R base64;                echo "==R base64 $?"
echo "==T md5sum";     $R md5sum a.txt;                    echo "==R md5sum $?"
echo "==T sha1sum";    $R sha1sum a.txt;                   echo "==R sha1sum $?"
echo "==T sha256sum";  $R sha256sum a.txt;                 echo "==R sha256sum $?"
echo "==T sha512sum";  $R sha512sum a.txt;                 echo "==R sha512sum $?"
echo "==T cksum";      $R cksum a.txt;                     echo "==R cksum $?"
echo "==T sum";        $R sum a.txt;                       echo "==R sum $?"
echo "==T uname";      $R uname -a;                        echo "==R uname $?"
echo "==T hostname";   $R hostname;                        echo "==R hostname $?"
echo "==T whoami";     $R whoami;                          echo "==R whoami $?"
echo "==T id";         $R id;                              echo "==R id $?"
echo "==T uptime";     $R uptime;                          echo "==R uptime $?"
echo "==T date";       $R date;                            echo "==R date $?"
echo "==T env";        $R env | $R head -1;                echo "==R env $?"
echo "==T printenv";   $R printenv PATH;                   echo "==R printenv $?"
echo "==T hostid";     $R hostid;                          echo "==R hostid $?"
echo "==T logname";    $R logname 2>/dev/null;             echo "==R logname $?"
echo "==T nproc";      $R nproc;                           echo "==R nproc $?"
echo "==T free";       $R free;                            echo "==R free $?"
echo "==T seq";        $R seq 3;                           echo "==R seq $?"
echo "==T yes";        $R yes | $R head -2;                echo "==R yes $?"
echo "==T sleep";      $R sleep 0;                         echo "==R sleep $?"
echo "==T which";      $R which rustfs 2>/dev/null;        echo "==R which $?"
echo "==T find";       $R find /t -name a.txt;             echo "==R find $?"
echo "==T test";       $R test 1 -eq 1;                    echo "==R test $?"
echo "==T expr";       $R expr 2 + 3;                      echo "==R expr $?"
echo "==T mktemp";     $R mktemp;                          echo "==R mktemp $?"
echo "==T cmp";        $R cmp a.txt a.txt;                 echo "==R cmp $?"
echo "==T length";     $R length abc;                      echo "==R length $?"
echo "==T cal";        $R cal 2>/dev/null;                 echo "==R cal $?"
echo "==T dc";         echo '2 3 + p' | $R dc;            echo "==R dc $?"
echo "==T expand";     printf 'a\tb\n' | $R expand;        echo "==R expand $?"
echo "==T unexpand";   echo 'a b' | $R unexpand;           echo "==R unexpand $?"
echo "==T split";      $R split -l1 lines.txt sp_ ;        echo "==R split $?"
echo "==T dos2unix";   $R dos2unix < a.txt >/dev/null;     echo "==R dos2unix $?"
echo "==T unix2dos";   $R unix2dos < a.txt >/dev/null;     echo "==R unix2dos $?"
echo "==T getopt";     $R getopt -o a -- -a 2>/dev/null;   echo "==R getopt $?"
echo "==T uuencode";   $R uuencode a.txt a.txt | $R head -1; echo "==R uuencode $?"

# compression roundtrip
echo "==T gzip";       $R gzip -c a.txt > a.gz;            echo "==R gzip $?"
echo "==T gunzip";     $R gunzip -c a.gz;                  echo "==R gunzip $?"
echo "==T zcat";       $R zcat a.gz;                       echo "==R zcat $?"
echo "==T bzip2";      $R bzip2 -c a.txt > a.bz2;          echo "==R bzip2 $?"
echo "==T bunzip2";    $R bunzip2 -c a.bz2;                echo "==R bunzip2 $?"
echo "==T bzcat";      $R bzcat a.bz2;                     echo "==R bzcat $?"
echo "==T ar";         $R ar rc arch.a a.txt 2>/dev/null;  echo "==R ar $?"

# system / proc dependent
echo "==T ps";         $R ps;                              echo "==R ps $?"
echo "==T mount";      $R mount;                           echo "==R mount $?"
echo "==T mountpoint";  $R mountpoint /proc;               echo "==R mountpoint $?"
echo "==T dmesg";      $R dmesg | $R tail -1;              echo "==R dmesg $?"
echo "==T lsmod";      $R lsmod;                           echo "==R lsmod $?"
echo "==T sync";       $R sync;                            echo "==R sync $?"
echo "==T fsync";      $R fsync a.txt;                     echo "==R fsync $?"
echo "==T pidof";      $R pidof init 2>/dev/null;          echo "==R pidof $?"
echo "==T sysctl";     $R sysctl kernel.hostname 2>/dev/null; echo "==R sysctl $?"
echo "==T blkid";      $R blkid 2>/dev/null;               echo "==R blkid $?"
echo "==T mknod";      $R mknod nd c 1 3;                  echo "==R mknod $?"
echo "==T mkfifo";     $R mkfifo ff;                       echo "==R mkfifo $?"
echo "==T tty";        $R tty;                             echo "==R tty $?"
echo "==T clear";      $R clear >/dev/null 2>&1;           echo "==R clear $?"
echo "==T ttysize";    $R ttysize 2>/dev/null;             echo "==R ttysize $?"
echo "==T setsid";     $R setsid $R true 2>/dev/null;      echo "==R setsid $?"
echo "==T usleep";     $R usleep 1000;                     echo "==R usleep $?"
echo "==T ipcalc";     $R ipcalc 192.168.1.1/24 2>/dev/null; echo "==R ipcalc $?"
echo "==T ifconfig";   $R ifconfig 2>/dev/null;            echo "==R ifconfig $?"
echo "==T ip";         $R ip addr 2>/dev/null;             echo "==R ip $?"
echo "==T arp";        $R arp 2>/dev/null;                 echo "==R arp $?"
echo "==T dnsdomainname"; $R dnsdomainname 2>/dev/null;    echo "==R dnsdomainname $?"
echo "==T devmem";     $R devmem 0x0 2>/dev/null;          echo "==R devmem $?"
echo "==T logger";     $R logger test 2>/dev/null;         echo "==R logger $?"
echo "==T xargs";      echo a | $R xargs $R echo;          echo "==R xargs $?"
echo "==T nohup";      $R nohup $R true 2>/dev/null;       echo "==R nohup $?"
echo "==T install";    $R install a.txt ins.txt 2>/dev/null; echo "==R install $?"
echo "==T truncate";   $R truncate -s 10 tr.bin;           echo "==R truncate $?"
echo "==T chattr";     $R chattr 2>/dev/null; echo "==R chattr ok"
echo "==T lsattr";     $R lsattr a.txt 2>/dev/null; echo "==R lsattr ok"
echo "==END=="
